<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Multiple regression and feature engineering | Advanced Sports Data Analysis</title>
  <meta name="description" content="This is the companion text to the University of Nebraska-Lincoln’s SPMC 460: Advanced Sports Data Analysis" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Multiple regression and feature engineering | Advanced Sports Data Analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the companion text to the University of Nebraska-Lincoln’s SPMC 460: Advanced Sports Data Analysis" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Multiple regression and feature engineering | Advanced Sports Data Analysis" />
  
  <meta name="twitter:description" content="This is the companion text to the University of Nebraska-Lincoln’s SPMC 460: Advanced Sports Data Analysis" />
  

<meta name="author" content="By Matt Waite" />


<meta name="date" content="2021-02-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="the-modeling-process.html"/>
<link rel="next" href="decision-trees-and-random-forests.html"/>
<script src="libs/header-attrs-2.5/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Advanced Sports Data Analysis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#requirements-and-conventions"><i class="fa fa-check"></i><b>1.1</b> Requirements and Conventions</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#about-this-book"><i class="fa fa-check"></i><b>1.2</b> About this book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="the-modeling-process.html"><a href="the-modeling-process.html"><i class="fa fa-check"></i><b>2</b> The modeling process</a>
<ul>
<li class="chapter" data-level="2.1" data-path="the-modeling-process.html"><a href="the-modeling-process.html#setting-up-the-modeling-process"><i class="fa fa-check"></i><b>2.1</b> Setting up the modeling process</a></li>
<li class="chapter" data-level="2.2" data-path="the-modeling-process.html"><a href="the-modeling-process.html#predicting-based-on-the-model"><i class="fa fa-check"></i><b>2.2</b> Predicting based on the model</a></li>
<li class="chapter" data-level="2.3" data-path="the-modeling-process.html"><a href="the-modeling-process.html#predicting-data-we-havent-seen-before"><i class="fa fa-check"></i><b>2.3</b> Predicting data we haven’t seen before</a></li>
<li class="chapter" data-level="2.4" data-path="the-modeling-process.html"><a href="the-modeling-process.html#looking-locally"><i class="fa fa-check"></i><b>2.4</b> Looking locally</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multiple-regression-and-feature-engineering.html"><a href="multiple-regression-and-feature-engineering.html"><i class="fa fa-check"></i><b>3</b> Multiple regression and feature engineering</a>
<ul>
<li class="chapter" data-level="3.1" data-path="multiple-regression-and-feature-engineering.html"><a href="multiple-regression-and-feature-engineering.html#a-multiple-regression-speed-run"><i class="fa fa-check"></i><b>3.1</b> A multiple regression speed run</a></li>
<li class="chapter" data-level="3.2" data-path="multiple-regression-and-feature-engineering.html"><a href="multiple-regression-and-feature-engineering.html#picking-what-moves-the-needle"><i class="fa fa-check"></i><b>3.2</b> Picking what moves the needle</a></li>
<li class="chapter" data-level="3.3" data-path="multiple-regression-and-feature-engineering.html"><a href="multiple-regression-and-feature-engineering.html#feature-engineering"><i class="fa fa-check"></i><b>3.3</b> Feature engineering</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="decision-trees-and-random-forests.html"><a href="decision-trees-and-random-forests.html"><i class="fa fa-check"></i><b>4</b> Decision trees and random forests</a>
<ul>
<li class="chapter" data-level="4.1" data-path="decision-trees-and-random-forests.html"><a href="decision-trees-and-random-forests.html#an-intro-to-pre-processing"><i class="fa fa-check"></i><b>4.1</b> An intro to pre-processing</a></li>
<li class="chapter" data-level="4.2" data-path="decision-trees-and-random-forests.html"><a href="decision-trees-and-random-forests.html#decision-trees"><i class="fa fa-check"></i><b>4.2</b> Decision trees</a></li>
<li class="chapter" data-level="4.3" data-path="decision-trees-and-random-forests.html"><a href="decision-trees-and-random-forests.html#random-forest"><i class="fa fa-check"></i><b>4.3</b> Random forest</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="xgboost.html"><a href="xgboost.html"><i class="fa fa-check"></i><b>5</b> XGBoost</a>
<ul>
<li class="chapter" data-level="5.1" data-path="xgboost.html"><a href="xgboost.html#hyperparameters"><i class="fa fa-check"></i><b>5.1</b> Hyperparameters</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="support-vector-machines.html"><a href="support-vector-machines.html"><i class="fa fa-check"></i><b>6</b> Support Vector Machines</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Advanced Sports Data Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multiple-regression-and-feature-engineering" class="section level1" number="3">
<h1><span class="header-section-number">Chapter 3</span> Multiple regression and feature engineering</h1>
<p>As we saw in the previous chapter, we can measure how much something can be predicted by another thing. We looked at how many points a team can score based on their shooting percentage. The theory being how well you shoot the ball probably has a lot to say about how many points you score. And what did we find? It’s about half the story.</p>
<p>But that raises the problem with simple regressions – they’re simple. Anyone who has watched a basketball game knows there’s a lot more to the outcome than just shooting prowess.</p>
<p>Enter the multiple regression.</p>
<p>Multiple regressions are a step toward reality – where more than one thing influences the outcome. However, the more variance we attempt to explain, the more error and uncertainty we introduce into our model.</p>
<p>Let’s begin by loading some libraries and installing a new one: <code>corrr</code></p>
<p>We install it by going to the console and typing <code>install.packages("corrr")</code></p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="multiple-regression-and-feature-engineering.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb37-2"><a href="multiple-regression-and-feature-engineering.html#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb37-3"><a href="multiple-regression-and-feature-engineering.html#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrr)</span></code></pre></div>
<p>For this, we’ll work with our college basketball game data and we’ll continue down the road we started in the last chapter.</p>
<pre><p><strong>For this walkthrough:</strong></p><p><a href="http://mattwaite.github.io/sportsdatafiles/cbblogs1521.csv">
  <button class="btn btn-danger"><i class="fa fa-save"></i> Download csv file</button>
</a></p></pre>
<p>Let’s import the data.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="multiple-regression-and-feature-engineering.html#cb38-1" aria-hidden="true" tabindex="-1"></a>games <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/cbblogs1521.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   .default = col_double(),
##   Season = col_character(),
##   Date = col_date(format = &quot;&quot;),
##   TeamFull = col_character(),
##   Opponent = col_character(),
##   HomeAway = col_character(),
##   W_L = col_character(),
##   URL = col_character(),
##   Conference = col_character(),
##   Team = col_character()
## )
## ℹ Use `spec()` for the full column specifications.</code></pre>
<div id="a-multiple-regression-speed-run" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> A multiple regression speed run</h2>
<p>First, let’s restore what we did in last chapter, spitting our data into training and testing, creating a linear model predicting score from the shooting percentage and producing the metrics for the results.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="multiple-regression-and-feature-engineering.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb40-2"><a href="multiple-regression-and-feature-engineering.html#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="multiple-regression-and-feature-engineering.html#cb40-3" aria-hidden="true" tabindex="-1"></a>game_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(games, <span class="at">prop =</span> .<span class="dv">8</span>)</span>
<span id="cb40-4"><a href="multiple-regression-and-feature-engineering.html#cb40-4" aria-hidden="true" tabindex="-1"></a>game_train <span class="ot">&lt;-</span> <span class="fu">training</span>(game_split)</span>
<span id="cb40-5"><a href="multiple-regression-and-feature-engineering.html#cb40-5" aria-hidden="true" tabindex="-1"></a>game_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(game_split)</span>
<span id="cb40-6"><a href="multiple-regression-and-feature-engineering.html#cb40-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-7"><a href="multiple-regression-and-feature-engineering.html#cb40-7" aria-hidden="true" tabindex="-1"></a>lm_model <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb40-8"><a href="multiple-regression-and-feature-engineering.html#cb40-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_engine</span>(<span class="st">&quot;lm&quot;</span>)</span>
<span id="cb40-9"><a href="multiple-regression-and-feature-engineering.html#cb40-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-10"><a href="multiple-regression-and-feature-engineering.html#cb40-10" aria-hidden="true" tabindex="-1"></a>fit_lm <span class="ot">&lt;-</span> lm_model <span class="sc">%&gt;%</span></span>
<span id="cb40-11"><a href="multiple-regression-and-feature-engineering.html#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(TeamScore <span class="sc">~</span> TeamFGPCT, <span class="at">data =</span> game_train)</span>
<span id="cb40-12"><a href="multiple-regression-and-feature-engineering.html#cb40-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-13"><a href="multiple-regression-and-feature-engineering.html#cb40-13" aria-hidden="true" tabindex="-1"></a>trainresults <span class="ot">&lt;-</span> game_train <span class="sc">%&gt;%</span></span>
<span id="cb40-14"><a href="multiple-regression-and-feature-engineering.html#cb40-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">bind_cols</span>(<span class="fu">predict</span>(fit_lm, game_train))</span>
<span id="cb40-15"><a href="multiple-regression-and-feature-engineering.html#cb40-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-16"><a href="multiple-regression-and-feature-engineering.html#cb40-16" aria-hidden="true" tabindex="-1"></a><span class="fu">metrics</span>(trainresults, <span class="at">truth =</span> TeamScore, <span class="at">estimate =</span> .pred)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard       9.31 
## 2 rsq     standard       0.505
## 3 mae     standard       7.25</code></pre>
<p>Bottom line: We can predict about 50 percent of the difference in team scores by the shooting percentage. But we know, because we’ve shot hoops in the driveway before, or went through a basketball unit in PE in the third grade, that sure, being a good shooter is important, but how many times you shoot the ball is also important. If you’re a 100 percent shooter, that’s insane, but it probably means you took one shot. Congrats, you scored two points (three if you’re gutsy). One shot is not going to win a game.</p>
<p>It would make sense, then, that we should combine the number of shots taken with the shooting percentage to predict the score. Doing that could not be easier. It’s literally adding <code>+ TeamFGA</code> to your fit function. Now our model says <code>TeamScore is approximately modeled by how well a team shoots the ball and how many shots they take</code>.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="multiple-regression-and-feature-engineering.html#cb42-1" aria-hidden="true" tabindex="-1"></a>fit_lm <span class="ot">&lt;-</span> lm_model <span class="sc">%&gt;%</span></span>
<span id="cb42-2"><a href="multiple-regression-and-feature-engineering.html#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(TeamScore <span class="sc">~</span> TeamFGPCT <span class="sc">+</span> TeamFGA, <span class="at">data =</span> game_train)</span>
<span id="cb42-3"><a href="multiple-regression-and-feature-engineering.html#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="multiple-regression-and-feature-engineering.html#cb42-4" aria-hidden="true" tabindex="-1"></a>trainresults <span class="ot">&lt;-</span> game_train <span class="sc">%&gt;%</span></span>
<span id="cb42-5"><a href="multiple-regression-and-feature-engineering.html#cb42-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">bind_cols</span>(<span class="fu">predict</span>(fit_lm, game_train))</span>
<span id="cb42-6"><a href="multiple-regression-and-feature-engineering.html#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="multiple-regression-and-feature-engineering.html#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="fu">metrics</span>(trainresults, <span class="at">truth =</span> TeamScore, <span class="at">estimate =</span> .pred)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard       6.44 
## 2 rsq     standard       0.763
## 3 mae     standard       5.13</code></pre>
<p>And just like that, by acknowledging reality, we’ve jumped to 76 percent of variance explained and our root mean squared error – the average amount we’re off by – has dropped from 9.3 to 6.5.</p>
<p>Your temptation now is to start adding things until we get to 1 on the r-squared and 0 on the rmse. The problem with that is called “overfitting”</p>
<p>Overfitting is where you produce a model that is too close to your training data, which makes it prone to fail with data you’ve never seen before – the model becomes unreliable when it’s not the training data anymore.</p>
<p>A secondary problem you encounter is this: the point of this is to predict future events. In this class, we’re attempting to predict the outcome of things that have not yet happened. That means we are going to be estimating the inputs to these models, inputs that will no doubt have error. So our inputs have a range of possible outcomes, our model is not perfect, so the outcome is going to combine the two. The more elements of your model that you use as inputs, the more error – uncertainty – you are introducing.</p>
<p>The point is you want to pick the things that really matter and ignore the rest in some vain quest to get to 100 percent. You won’t get there.</p>
</div>
<div id="picking-what-moves-the-needle" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> Picking what moves the needle</h2>
<p>There are multiple ways to find the right combination of inputs to your models. With multiple regressions, the most common is the correlation matrix. We’re looking to maximize r-squared by choosing inputs that are highly correlated to our target value, but <em>not</em> correlated with other things. Example: We can assume that TeamFG and TeamFGPCT are highly correlated to TeamScore, but the number of Field Goals made is also highly correlated with the field goal percentage.</p>
<p>Using <code>corrr</code>, we can create a correlation matrix in a dataframe and use filter to find columns that are highly correlated with our target – team score. To do this, we need to drop all non-numeric data, then we need to dump one numeric variable that isn’t really a number - the game number of the season. To narrow in a bit, we’ll select just two columns to get a view of things, which we will have to expand upon soon.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="multiple-regression-and-feature-engineering.html#cb44-1" aria-hidden="true" tabindex="-1"></a>games <span class="sc">%&gt;%</span> </span>
<span id="cb44-2"><a href="multiple-regression-and-feature-engineering.html#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_if</span>(is.numeric) <span class="sc">%&gt;%</span> </span>
<span id="cb44-3"><a href="multiple-regression-and-feature-engineering.html#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Game) <span class="sc">%&gt;%</span> </span>
<span id="cb44-4"><a href="multiple-regression-and-feature-engineering.html#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlate</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb44-5"><a href="multiple-regression-and-feature-engineering.html#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(TeamScore <span class="sc">&gt;</span> .<span class="dv">4</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb44-6"><a href="multiple-regression-and-feature-engineering.html#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, TeamScore)</span></code></pre></div>
<pre><code>## # A tibble: 7 x 2
##   term        TeamScore
##   &lt;chr&gt;           &lt;dbl&gt;
## 1 TeamFG          0.874
## 2 TeamFGA         0.435
## 3 TeamFGPCT       0.709
## 4 Team3P          0.512
## 5 Team3PPCT       0.473
## 6 TeamFT          0.417
## 7 TeamAssists     0.638</code></pre>
<p>By this, there’s seven things correlated with TeamScore at a greater than .4 level. However, this is half the story. The issue becomes how correlated are those things to each other. To see that, we need to fix our select:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="multiple-regression-and-feature-engineering.html#cb46-1" aria-hidden="true" tabindex="-1"></a>games <span class="sc">%&gt;%</span> </span>
<span id="cb46-2"><a href="multiple-regression-and-feature-engineering.html#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_if</span>(is.numeric) <span class="sc">%&gt;%</span> </span>
<span id="cb46-3"><a href="multiple-regression-and-feature-engineering.html#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Game) <span class="sc">%&gt;%</span> </span>
<span id="cb46-4"><a href="multiple-regression-and-feature-engineering.html#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlate</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb46-5"><a href="multiple-regression-and-feature-engineering.html#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(TeamScore <span class="sc">&gt;</span> .<span class="dv">4</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb46-6"><a href="multiple-regression-and-feature-engineering.html#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, TeamScore, TeamFG, TeamFGA, TeamFGPCT, Team3P, Team3PPCT, TeamFT, TeamAssists)</span></code></pre></div>
<pre><code>## # A tibble: 7 x 9
##   term  TeamScore  TeamFG TeamFGA TeamFGPCT Team3P Team3PPCT   TeamFT
##   &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 Team…     0.874 NA       0.564     0.757   0.407   0.380   -0.0201 
## 2 Team…     0.435  0.564  NA        -0.0994  0.217  -0.0951  -0.134  
## 3 Team…     0.709  0.757  -0.0994   NA       0.321   0.541    0.0820 
## 4 Team…     0.512  0.407   0.217     0.321  NA       0.711   -0.102  
## 5 Team…     0.473  0.380  -0.0951    0.541   0.711  NA        0.00894
## 6 Team…     0.417 -0.0201 -0.134     0.0820 -0.102   0.00894 NA      
## 7 Team…     0.638  0.662   0.290     0.562   0.525   0.433   -0.0181 
## # … with 1 more variable: TeamAssists &lt;dbl&gt;</code></pre>
<p>Reading this can be a lot, and it helps to take some notes as you go.</p>
<p>TeamFG is the most correlated to TeamScore – which makes sense. Made shots are points. But they’re also highly correlated to attempts and even more to percentage. There’s others that it’s highly correlated with.</p>
<p>Attempts are moderately associated with TeamScore, but notice they are NOT correlated with TeamFGPCT. What does that tell you? It says teams shoot the ball, regardless of how good they are at it, and the two aren’t related to each other BUT they are related to the points teams score. Perfect.</p>
</div>
<div id="feature-engineering" class="section level2" number="3.3">
<h2><span class="header-section-number">3.3</span> Feature engineering</h2>
<p>Feature engineering is the process of using what you know about something – domain knowledge – to find features in data that can be used in machine learning algorithms. Sports is a great place for this because not only do we know a lot because we follow the sport, but lots of other people are looking at this all the time. Creativity is good.</p>
<p>Let’s look at basketball games again.</p>
<p>A number of basketball heads – including Ken Pomeroy of KenPom fame – have noticed that one of the predictors of the outcome of basketball games are possession metrics. How efficient are teams with the possessions they have? Can’t score if you don’t have the ball, so how good is a team at pushing the play and getting more possessions, giving themselves more chances to score?</p>
<p>One problem? Possessions aren’t in typical metrics. They aren’t usually tracked. But you can estimate them from typical box scores. The way to do that is like this:</p>
<p><code>Possessions = Field Goal Attempts – Offensive Rebounds + Turnovers + (0.475 * Free Throw Attempts)</code></p>
<p>Here is that formula applied to our data, plus creating some new metrics of Points Per Possession for both Team and Opponent:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="multiple-regression-and-feature-engineering.html#cb48-1" aria-hidden="true" tabindex="-1"></a>gameswithpossessions <span class="ot">&lt;-</span> games <span class="sc">%&gt;%</span> </span>
<span id="cb48-2"><a href="multiple-regression-and-feature-engineering.html#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb48-3"><a href="multiple-regression-and-feature-engineering.html#cb48-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">TeamPossessions =</span> TeamFGA <span class="sc">-</span> TeamOffRebounds <span class="sc">+</span> TeamTurnovers <span class="sc">+</span> (.<span class="dv">475</span> <span class="sc">*</span> TeamFTA), </span>
<span id="cb48-4"><a href="multiple-regression-and-feature-engineering.html#cb48-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">OpponentPossessions =</span> OpponentFGA <span class="sc">-</span> OpponentOffRebounds <span class="sc">+</span> OpponentTurnovers <span class="sc">+</span> (.<span class="dv">475</span> <span class="sc">*</span> OpponentFTA), </span>
<span id="cb48-5"><a href="multiple-regression-and-feature-engineering.html#cb48-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">TeamPPP =</span> TeamScore<span class="sc">/</span>TeamPossessions, </span>
<span id="cb48-6"><a href="multiple-regression-and-feature-engineering.html#cb48-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">OpponentPPP =</span> OpponentScore<span class="sc">/</span>OpponentPossessions)</span></code></pre></div>
<p>Now lets look at the correlation matrix for our newly added data:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="multiple-regression-and-feature-engineering.html#cb49-1" aria-hidden="true" tabindex="-1"></a>gameswithpossessions <span class="sc">%&gt;%</span> </span>
<span id="cb49-2"><a href="multiple-regression-and-feature-engineering.html#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_if</span>(is.numeric) <span class="sc">%&gt;%</span> </span>
<span id="cb49-3"><a href="multiple-regression-and-feature-engineering.html#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Game) <span class="sc">%&gt;%</span> </span>
<span id="cb49-4"><a href="multiple-regression-and-feature-engineering.html#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlate</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb49-5"><a href="multiple-regression-and-feature-engineering.html#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(TeamScore <span class="sc">&gt;</span> .<span class="dv">4</span>) <span class="sc">%&gt;%</span></span>
<span id="cb49-6"><a href="multiple-regression-and-feature-engineering.html#cb49-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, TeamScore)</span></code></pre></div>
<pre><code>## # A tibble: 10 x 2
##    term                TeamScore
##    &lt;chr&gt;                   &lt;dbl&gt;
##  1 TeamFG                  0.874
##  2 TeamFGA                 0.435
##  3 TeamFGPCT               0.709
##  4 Team3P                  0.512
##  5 Team3PPCT               0.473
##  6 TeamFT                  0.417
##  7 TeamAssists             0.638
##  8 TeamPossessions         0.533
##  9 OpponentPossessions     0.555
## 10 TeamPPP                 0.850</code></pre>
<p>Note: our new possession metrics now make the grade here. But are they correlated with each other?</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="multiple-regression-and-feature-engineering.html#cb51-1" aria-hidden="true" tabindex="-1"></a>gameswithpossessions <span class="sc">%&gt;%</span> </span>
<span id="cb51-2"><a href="multiple-regression-and-feature-engineering.html#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_if</span>(is.numeric) <span class="sc">%&gt;%</span> </span>
<span id="cb51-3"><a href="multiple-regression-and-feature-engineering.html#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Game) <span class="sc">%&gt;%</span> </span>
<span id="cb51-4"><a href="multiple-regression-and-feature-engineering.html#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlate</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb51-5"><a href="multiple-regression-and-feature-engineering.html#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(TeamScore <span class="sc">&gt;</span> .<span class="dv">4</span>) <span class="sc">%&gt;%</span></span>
<span id="cb51-6"><a href="multiple-regression-and-feature-engineering.html#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, TeamScore, TeamFG, TeamFGA, TeamFGPCT, Team3P, Team3PPCT, TeamFT, TeamAssists, TeamPossessions, OpponentPossessions, TeamPPP)</span></code></pre></div>
<pre><code>## # A tibble: 10 x 12
##    term  TeamScore  TeamFG TeamFGA TeamFGPCT Team3P Team3PPCT   TeamFT
##    &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
##  1 Team…     0.874 NA       0.564     0.757   0.407   0.380   -0.0201 
##  2 Team…     0.435  0.564  NA        -0.0994  0.217  -0.0951  -0.134  
##  3 Team…     0.709  0.757  -0.0994   NA       0.321   0.541    0.0820 
##  4 Team…     0.512  0.407   0.217     0.321  NA       0.711   -0.102  
##  5 Team…     0.473  0.380  -0.0951    0.541   0.711  NA        0.00894
##  6 Team…     0.417 -0.0201 -0.134     0.0820 -0.102   0.00894 NA      
##  7 Team…     0.638  0.662   0.290     0.562   0.525   0.433   -0.0181 
##  8 Team…     0.533  0.439   0.613     0.0504  0.143  -0.0235   0.335  
##  9 Oppo…     0.555  0.449   0.536     0.122   0.170   0.0307   0.352  
## 10 Team…     0.850  0.757   0.134     0.810   0.517   0.578    0.286  
## # … with 4 more variables: TeamAssists &lt;dbl&gt;, TeamPossessions &lt;dbl&gt;,
## #   OpponentPossessions &lt;dbl&gt;, TeamPPP &lt;dbl&gt;</code></pre>
<p>Let’s look specifically at our TeamPPP and TeamPossessions metrics. Both are correlated to TeamScore – TeamPPP is highly correlated – but they AREN’T very correlated to each other. If you think about it, it makes some sense: one is a measure of how good the team is at getting the ball into their hands, the other is a measure of how efficient they are at scoring when they have the ball. Both metrics encompass a lot about a game – steals, rebounds, free throws, etc. – that basic shooting metrics don’t give you.</p>
<p>So how does this look in a model?</p>
<p>First, there’s a very small number of games with blanks for some of shooting stats, so we need to dump them first or we’ll get errors.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="multiple-regression-and-feature-engineering.html#cb53-1" aria-hidden="true" tabindex="-1"></a>gameswithpossessions <span class="ot">&lt;-</span> gameswithpossessions <span class="sc">%&gt;%</span> <span class="fu">filter</span>(TeamFGPCT<span class="sc">&gt;</span><span class="dv">0</span>, OpponentFGPCT<span class="sc">&gt;</span><span class="dv">0</span>)</span></code></pre></div>
<p>First we split our data into training and testing.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="multiple-regression-and-feature-engineering.html#cb54-1" aria-hidden="true" tabindex="-1"></a>newgame_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(gameswithpossessions, <span class="at">prop =</span> .<span class="dv">8</span>)</span>
<span id="cb54-2"><a href="multiple-regression-and-feature-engineering.html#cb54-2" aria-hidden="true" tabindex="-1"></a>newgame_train <span class="ot">&lt;-</span> <span class="fu">training</span>(newgame_split)</span>
<span id="cb54-3"><a href="multiple-regression-and-feature-engineering.html#cb54-3" aria-hidden="true" tabindex="-1"></a>newgame_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(newgame_split)</span></code></pre></div>
<p>Create the model shell.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="multiple-regression-and-feature-engineering.html#cb55-1" aria-hidden="true" tabindex="-1"></a>lm_model <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb55-2"><a href="multiple-regression-and-feature-engineering.html#cb55-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_engine</span>(<span class="st">&quot;lm&quot;</span>)</span></code></pre></div>
<p>Create the fit.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="multiple-regression-and-feature-engineering.html#cb56-1" aria-hidden="true" tabindex="-1"></a>fit_lm <span class="ot">&lt;-</span> lm_model <span class="sc">%&gt;%</span></span>
<span id="cb56-2"><a href="multiple-regression-and-feature-engineering.html#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(TeamScore <span class="sc">~</span> TeamPossessions <span class="sc">+</span> TeamPPP, <span class="at">data =</span> newgame_train)</span></code></pre></div>
<p>Let’s take a peek at our model coefficients.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="multiple-regression-and-feature-engineering.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(fit_lm, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 7
##   term            estimate std.error statistic p.value conf.low conf.high
##   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)       -72.1   0.0594      -1214.       0   -72.2     -72.0 
## 2 TeamPossessions     1.02  0.000718     1422.       0     1.02      1.02
## 3 TeamPPP            70.6   0.0308       2294.       0    70.5      70.6</code></pre>
<p>What this says is if we have zero possessions in a basketball game, we’ll score -72 points. Well, we know neither are possible, so we ignore that. The model says for each possession, we should score about 1.02 points, and if we were to score 1 point per possession, we’d score 70.6 points. Now we play the games.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="multiple-regression-and-feature-engineering.html#cb59-1" aria-hidden="true" tabindex="-1"></a>trainresults <span class="ot">&lt;-</span> newgame_train <span class="sc">%&gt;%</span></span>
<span id="cb59-2"><a href="multiple-regression-and-feature-engineering.html#cb59-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">bind_cols</span>(<span class="fu">predict</span>(fit_lm, newgame_train))</span></code></pre></div>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="multiple-regression-and-feature-engineering.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">metrics</span>(trainresults, <span class="at">truth =</span> TeamScore, <span class="at">estimate =</span> .pred)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard       1.09 
## 2 rsq     standard       0.993
## 3 mae     standard       0.658</code></pre>
<p>So … knowing possession metrics makes you VERY good at predicting the total points a team will score. That’s frighteningly high — overfitting high. But we’ll continue to test it out.</p>
<p>How well does the model do with data it hasn’t seen before?</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="multiple-regression-and-feature-engineering.html#cb62-1" aria-hidden="true" tabindex="-1"></a>testresults <span class="ot">&lt;-</span> newgame_test <span class="sc">%&gt;%</span></span>
<span id="cb62-2"><a href="multiple-regression-and-feature-engineering.html#cb62-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">bind_cols</span>(<span class="fu">predict</span>(fit_lm, newgame_test))</span></code></pre></div>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="multiple-regression-and-feature-engineering.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">metrics</span>(testresults, <span class="at">truth =</span> TeamScore, <span class="at">estimate =</span> .pred)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard       1.05 
## 2 rsq     standard       0.994
## 3 mae     standard       0.652</code></pre>
<p>Again … somewhat terrifyingly well.</p>
<p>Let’s put this against a set of games we’re familiar with.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="multiple-regression-and-feature-engineering.html#cb65-1" aria-hidden="true" tabindex="-1"></a>nu <span class="ot">&lt;-</span> gameswithpossessions <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Season <span class="sc">==</span> <span class="st">&quot;2020-2021&quot;</span>, TeamFull <span class="sc">==</span> <span class="st">&quot;Nebraska Cornhuskers&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="multiple-regression-and-feature-engineering.html#cb66-1" aria-hidden="true" tabindex="-1"></a>nupreds <span class="ot">&lt;-</span> nu <span class="sc">%&gt;%</span></span>
<span id="cb66-2"><a href="multiple-regression-and-feature-engineering.html#cb66-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">bind_cols</span>(<span class="fu">predict</span>(fit_lm, nu))</span></code></pre></div>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="multiple-regression-and-feature-engineering.html#cb67-1" aria-hidden="true" tabindex="-1"></a>nupreds <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Residual =</span> TeamScore <span class="sc">-</span> .pred) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Residual)) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Team, Opponent, TeamScore, .pred, Residual)</span></code></pre></div>
<pre><code>## # A tibble: 19 x 5
##    Team     Opponent           TeamScore .pred Residual
##    &lt;chr&gt;    &lt;chr&gt;                  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
##  1 Nebraska Doane College            110 107.    3.47  
##  2 Nebraska McNeese State            102  99.6   2.44  
##  3 Nebraska Wisconsin                 48  46.7   1.32  
##  4 Nebraska Wisconsin                 53  52.0   0.977 
##  5 Nebraska Maryland                  50  49.5   0.542 
##  6 Nebraska North Dakota State        79  78.9   0.117 
##  7 Nebraska Michigan State            77  76.9   0.0673
##  8 Nebraska Indiana                   76  76.0   0.0382
##  9 Nebraska Penn State                62  62.0   0.0102
## 10 Nebraska Maryland                  71  71.0  -0.0358
## 11 Nebraska Georgia Tech              64  64.1  -0.0782
## 12 Nebraska Illinois                  72  72.4  -0.396 
## 13 Nebraska Michigan                  69  69.5  -0.541 
## 14 Nebraska South Dakota              76  76.6  -0.554 
## 15 Nebraska Nevada                    66  66.7  -0.686 
## 16 Nebraska Creighton                 74  75.7  -1.75  
## 17 Nebraska Ohio State                54  56.1  -2.06  
## 18 Nebraska Minnesota                 61  63.1  -2.07  
## 19 Nebraska Michigan State            56  59.2  -3.20</code></pre>
<p>Our multiple regression model does the worst with blowouts, but it’s within a point on most games.</p>
<p>The question to start thinking about is this – how well can you predict the number of possessions a team will have going into a game, and how many points they’ll score on each of those possessions?</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="the-modeling-process.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="decision-trees-and-random-forests.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/02-multipleregression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["advancedsportsdataanalysis.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
